{
  "hash": "f84dde17b1f155c0df60ec52ce08e3d4",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Exploring Global Development Patterns with World Bank Data\"\ndescription: \"An exploratory data analysis using Stata to investigate GDP, literacy rates, and mortality indicators across countries\"\nauthor: \"Nadhira A. Hendra\"\ncategories: [stata, development-economics, regression]\ndate: \"January 12, 2026\"\ndate-modified: \"January 13, 2026\"\nformat:\n  html:\n    code-fold: true\n    toc: true\n    toc-depth: 3\nexecute:\n  eval: true\n  echo: true\n---\n\n\n# Introduction\n\nThis analysis started as one of my class assignment. The task was to explore World Bank development indicators, how GDP per capita relates to literacy rates, infant mortality, and income inequality across countries.\n\nIn my previous role at Traveloka, most of my analytical work centered on SQL and Python. For this project, I wanted to demonstrate my statistical analysis capabilities using Stata, focusing on regression techniques and econometric approaches to understanding development patterns.\n\nI hope this serves as both a personal reference and a resource for others working with similar datasets.\n\n# Problem\nThe key questions we're trying to answer in this analysis is:\n\n- How unequal is global income distribution?\n- What patterns emerge when comparing the richest and poorest countries?\n- Can simple regression models capture the relationships between income, education, and health?\n\n# Exploratory Analysis\n## Setup\n\nTo Setup stata in R, we use `Statamarkdown` library. It is a free open-source R package available on CRAN and Github. However, while the package is free, we still need to have Stata installed in the computer for the library to function. At the moment of making this article I have the Basic one (StataBE) in my computer. \n\nAs you can see below I add an `engine.path` in which this specify the location of the App. Since my Stata is in the application folder, knitr wouldn't find it automatically and Stata could fail to execute. When the setup is done, we can continue with data preparation!\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nlibrary(Statamarkdown)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nStata found at /Applications/StataNow/StataBE.app/Contents/MacOS/StataBE\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nThe 'stata' engine is ready to use.\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\nknitr::opts_chunk$set(\n  warning=FALSE,\n  message=FALSE,\n  engine.path = list(stata = \"/Applications/StataNow/StataBE.app/Contents/MacOS/StataBE\")\n  )\n```\n:::\n\n\n## Data Cleaning and Preparation\n\nThe World Bank Development Indicators dataset contains panel data spanning 2015-2024, the data itself can be obtain from this website here [World Bank DataBank](https://databank.worldbank.org/source/world-development-indicators). The raw data requires substantial amount of cleaning before we can explore further\n\n\n::: {.cell}\n\n```{.stata .cell-code}\n\nclear\n\n/* a) Import CSV with proper variable types */\nimport delimited \"wb_indicators_2015_2024.csv\", varnames(1) ///\n    numericcols(5 6 7 8 9 10 11 12 13 14)\n\n/* b) Examine initial data structure. */\ndescribe\n\n/* c) Generate row id and remove regional aggregates. Upon eyeballing the data we observe that entries after row 1085 are regional/world aggregates */\ngenerate id = _n\nkeep if id < 1086\n\n/* d) Reshape from wide to long format and use the column name as the value for yr */\nreshape long yr, i(id) j(year)\nrename yr seriesvalue\n\n/* e) Since we found several countries with some years that have null indicator, we further clean the data by keeping most recent non-missing value per country-indicator */\ngsort countrycode seriescode -year\nkeep if seriesvalue < .\ngsort seriescode seriesname countrycode countryname -year\nby seriescode seriesname countrycode countryname: keep if _n == 1\nsort countryname seriescode\n\n* Save cleaned long-format data\nsave \"wb_cleaned_long.dta\", replace\n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(encoding automatically selected: ISO-8859-1)\n(14 vars, 1,330 obs)\n\n\nContains data\n Observations:         1,330                  \n    Variables:            14                  \n-------------------------------------------------------------------------------------------\nVariable      Storage   Display    Value\n    name         type    format    label      Variable label\n-------------------------------------------------------------------------------------------\ncountryname     str73   %73s                  Country Name\ncountrycode     str3    %9s                   Country Code\nseriesname      str60   %60s                  Series Name\nseriescode      str17   %17s                  Series Code\nyr2015          float   %8.0g                 2015 [YR2015]\nyr2016          float   %8.0g                 2016 [YR2016]\nyr2017          float   %8.0g                 2017 [YR2017]\nyr2018          float   %8.0g                 2018 [YR2018]\nyr2019          float   %8.0g                 2019 [YR2019]\nyr2020          float   %8.0g                 2020 [YR2020]\nyr2021          float   %8.0g                 2021 [YR2021]\nyr2022          float   %8.0g                 2022 [YR2022]\nyr2023          float   %8.0g                 2023 [YR2023]\nyr2024          float   %8.0g                 2024 [YR2024]\n-------------------------------------------------------------------------------------------\nSorted by: \n     Note: Dataset has changed since last saved.\n\n\n(245 observations deleted)\n\n(j = 2015 2016 2017 2018 2019 2020 2021 2022 2023 2024)\n\nData                               Wide   ->   Long\n-----------------------------------------------------------------------------\nNumber of observations            1,085   ->   10,850      \nNumber of variables                  15   ->   7           \nj variable (10 values)                    ->   year\nxij variables:\n               yr2015 yr2016 ... yr2024   ->   yr\n-----------------------------------------------------------------------------\n\n\n\n(5,937 observations deleted)\n\n\n(4,063 observations deleted)\n\n\nfile wb_cleaned_long.dta saved\n```\n\n\n:::\n:::\n\n\n## Descriptive Statistics by indicator\n\nWith the cleaned data, we now can examine the distribution of each development indicator across countries. Since the nature of the library (it cannot save last data transformation between chunks), we need to load the dataset everytime we wanted to explore and save the data after we made changes in the data.\n\n\n::: {.cell}\n\n```{.stata .cell-code}\n* Load cleaned data\nuse \"wb_cleaned_long.dta\", clear\n\n* Summary statistics by indicator\nbysort seriesname: summarize seriesvalue\n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\n-> seriesname = GDP per capita (current US$)\n\n    Variable |        Obs        Mean    Std. dev.       Min        Max\n-------------+---------------------------------------------------------\n seriesvalue |        212    22654.69    33300.99   153.9302   256580.5\n\n-------------------------------------------------------------------------------------------\n-> seriesname = Literacy rate, adult female (% of fema..\n\n    Variable |        Obs        Mean    Std. dev.       Min        Max\n-------------+---------------------------------------------------------\n seriesvalue |        152    82.10739    21.35883      18.87        100\n\n-------------------------------------------------------------------------------------------\n-> seriesname = Literacy rate, adult male (% of males ..\n\n    Variable |        Obs        Mean    Std. dev.       Min        Max\n-------------+---------------------------------------------------------\n seriesvalue |        145    87.76561    15.06481      35.78        100\n\n-------------------------------------------------------------------------------------------\n-> seriesname = Literacy rate, adult total (% of peopl..\n\n    Variable |        Obs        Mean    Std. dev.       Min        Max\n-------------+---------------------------------------------------------\n seriesvalue |        145    84.76617     18.2601      27.28        100\n\n-------------------------------------------------------------------------------------------\n-> seriesname = Mortality rate, infant (per 1,000 live..\n\n    Variable |        Obs        Mean    Std. dev.       Min        Max\n-------------+---------------------------------------------------------\n seriesvalue |        196    18.76224    16.70753        1.4       72.6\n```\n\n\n:::\n:::\n\n\nThe summary statistics reveal variation across all indicators. GDP per capita ranges from under \\$300 to over \\$100,000, while literacy rates span from 27% to nearly 100%. This indicates that there's wide gap between literacy rate among low and high income countries\n\n## Reshape to look deeper into the indicators\n\nTo analyze relationships between indicators, we need to reshape the data to wide format where each country is one observation with separate columns for each indicator. We also will replace some series code so that it is more intepretable by the readers.\n\n\n::: {.cell}\n\n```{.stata .cell-code}\n* Load cleaned data\nuse \"wb_cleaned_long.dta\", clear\n\n* Rename series codes for readability\nreplace seriescode = \"gdp\" if seriescode == \"NY.GDP.PCAP.CD\"\nreplace seriescode = \"female_literacy\" if seriescode == \"SE.ADT.LITR.FE.ZS\"\nreplace seriescode = \"male_literacy\" if seriescode == \"SE.ADT.LITR.MA.ZS\"\nreplace seriescode = \"adult_literacy\" if seriescode == \"SE.ADT.LITR.ZS\"\nreplace seriescode = \"mortality\" if seriescode == \"SP.DYN.IMRT.IN\"\n\n* Drop unnecessary variables and reshape wide\ndrop id year seriesname\nreshape wide seriesvalue, i(countrycode countryname) j(seriescode) string\n\n* Rename variables for clarity\nrename seriesvaluegdp gdp\nrename seriesvaluefemale_literacy female_literacy\nrename seriesvaluemale_literacy male_literacy\nrename seriesvalueadult_literacy adult_literacy\nrename seriesvaluemortality mortality\n\n* Save wide-format data for analysis\nsave \"wb_cleaned_wide.dta\", replace\n\ndescribe\n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(212 real changes made)\n\n(152 real changes made)\n\n(145 real changes made)\n\n(145 real changes made)\n\n(196 real changes made)\n\n\n(j = adult_literacy female_literacy gdp male_literacy mortality)\n\nData                               Long   ->   Wide\n-----------------------------------------------------------------------------\nNumber of observations              850   ->   216         \nNumber of variables                   4   ->   7           \nj variable (5 values)        seriescode   ->   (dropped)\nxij variables:\n                            seriesvalue   ->   seriesvalueadult_literacy seriesvaluefemale_\n> literacy ... seriesvaluemortality\n-----------------------------------------------------------------------------\n\n\n\n\n\n\nfile wb_cleaned_wide.dta saved\n\n\nContains data from wb_cleaned_wide.dta\n Observations:           216                  \n    Variables:             7                  13 Jan 2026 23:26\n-------------------------------------------------------------------------------------------\nVariable      Storage   Display    Value\n    name         type    format    label      Variable label\n-------------------------------------------------------------------------------------------\ncountrycode     str3    %9s                   Country Code\ncountryname     str73   %73s                  Country Name\nadult_literacy  float   %8.0g                 adult_literacy seriesvalue\nfemale_literacy float   %8.0g                 female_literacy seriesvalue\ngdp             float   %8.0g                 gdp seriesvalue\nmale_literacy   float   %8.0g                 male_literacy seriesvalue\nmortality       float   %8.0g                 mortality seriesvalue\n-------------------------------------------------------------------------------------------\nSorted by: countrycode  countryname\n```\n\n\n:::\n:::\n\n\n## Comparing Rich and Poor Countries\n\nOne of the way to make the difference obvious between countries to show how severe the inequality is by comparing development outcomes between the richest and poorest countries by GDP per capita. In the table below we will compare the literacy and mortality across top 50 and bottom 50 countries\n\n\n::: {.cell}\n\n```{.stata .cell-code}\n* Load wide-format data\nuse \"wb_cleaned_wide.dta\", clear\n\n* Top 50 countries by GDP per capita\ndisplay \"=== TOP 50 COUNTRIES BY GDP PER CAPITA ===\"\ngsort -gdp\nsummarize adult_literacy female_literacy male_literacy mortality in 1/50\n\n* Bottom 50 countries by GDP per capita\ndisplay \"\"\ndisplay \"=== BOTTOM 50 COUNTRIES BY GDP PER CAPITA ===\"\nsort gdp\nsummarize adult_literacy female_literacy male_literacy mortality in 1/50\n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=== TOP 50 COUNTRIES BY GDP PER CAPITA ===\n\n    Variable |        Obs        Mean    Std. dev.       Min        Max\n-------------+---------------------------------------------------------\nadult_lite~y |         14    97.79929    1.973078       92.4        100\nfemale_lit~y |         14      97.365     1.95109       92.4        100\nmale_liter~y |         14    98.09429     2.25755       92.4        100\n   mortality |         35    3.451429    1.937763        1.4       11.4\n\n\n\n=== BOTTOM 50 COUNTRIES BY GDP PER CAPITA ===\n\n    Variable |        Obs        Mean    Std. dev.       Min        Max\n-------------+---------------------------------------------------------\nadult_lite~y |         47    65.98271    19.28016      27.28       99.6\nfemale_lit~y |         49    60.33596    22.55905      18.87       99.5\nmale_liter~y |         47    72.53659    16.63416      35.78       99.7\n   mortality |         50      39.714    14.24526       14.3       72.6\n```\n\n\n:::\n:::\n\n\nThe gap is striking for infant mortality, the highest mortality rate among wealthy countries (11.4 death per 1000 live births) is lower than the lowest rate among poor countries (14.3 death per 1000 live births). It indicates a wide gap and systemic differences in health infrastructure.\n\n## Distribution Analysis\n\nThe distribution of GDP per capita reveals important insights about global inequality. The median (\\$8536) is much lower than the Mean (\\$22654) which indicates there's more low income countries globally\n\n\n::: {.cell}\n\n```{.stata .cell-code}\n* Load wide-format data\nuse \"wb_cleaned_wide.dta\", clear\n\n* Detailed distribution statistics\nsummarize gdp, detail\n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                       gdp seriesvalue\n-------------------------------------------------------------\n      Percentiles      Smallest\n 1%      433.174       153.9302\n 5%     806.9457       413.7579\n10%     1016.089        433.174       Obs                 212\n25%     2703.279       508.3713       Sum of wgt.         212\n\n50%     8536.106                      Mean           22654.69\n                        Largest       Std. dev.      33300.99\n75%     31438.36       137516.6\n90%      56833.2         138935       Variance       1.11e+09\n95%      85809.9       207973.6       Skewness       3.302677\n99%       138935       256580.5       Kurtosis       18.64592\n```\n\n\n:::\n:::\n\n\n## Regression Analysis\n::: {.callout-tip}\n## Correlation vs. Causation\n\nIn this document, with the correlational relationships that is present, we cannot claim that increasing GDP would *cause* mortality to fall. Reason is because in data without randomization presents, there could be reverse causality (e.g Lower mortality might cause countries to grow faster instead of Rich countries might cause lower mortality rates), or omitted variables (e.g like institutional quality could drive both mortality and gdp). To reduce this possibility we would require randomization or quasi-experimental methods like Regression Discontinuity Design or Instrumental Variables. Hence ***all the interpretation here is not causal***\n:::\n\n### Infant Mortality on GDP Per Capita\n\n\n::: {.cell}\n\n```{.stata .cell-code}\n* Load wide-format data\nuse \"wb_cleaned_wide.dta\", clear\n\n* Regression: infant mortality on GDP per capita\nregress mortality gdp\n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Source |       SS           df       MS      Number of obs   =       192\n-------------+----------------------------------   F(1, 190)       =     56.73\n       Model |  12487.5383         1  12487.5383   Prob > F        =    0.0000\n    Residual |  41822.6659       190  220.119294   R-squared       =    0.2299\n-------------+----------------------------------   Adj R-squared   =    0.2259\n       Total |  54310.2041       191  284.346619   Root MSE        =    14.836\n\n------------------------------------------------------------------------------\n   mortality | Coefficient  Std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n         gdp |   -.000278   .0000369    -7.53   0.000    -.0003508   -.0002052\n       _cons |   23.98073   1.274607    18.81   0.000     21.46654    26.49493\n------------------------------------------------------------------------------\n```\n\n\n:::\n:::\n\n\nEach additional \\$1,000 in GDP per capita is associated with approximately 0.27 fewer infant deaths per 1,000 live births. The negative coefficient aligns with expectations: wealthier countries typically have better healthcare infrastructure. And the difference is statistically significant with p-value < 0.05\n\n### Literacy on GDP Per Capita\n\n\n::: {.cell}\n\n```{.stata .cell-code}\n* Load wide-format data\nuse \"wb_cleaned_wide.dta\", clear\n\n* Regression: adult literacy on GDP per capita\nregress adult_literacy gdp\n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Source |       SS           df       MS      Number of obs   =       142\n-------------+----------------------------------   F(1, 140)       =     33.03\n       Model |  9077.13217         1  9077.13217   Prob > F        =    0.0000\n    Residual |  38470.2731       140  274.787665   R-squared       =    0.1909\n-------------+----------------------------------   Adj R-squared   =    0.1851\n       Total |  47547.4053       141   337.21564   Root MSE        =    16.577\n\n------------------------------------------------------------------------------\nadult_lite~y | Coefficient  Std. err.      t    P>|t|     [95% conf. interval]\n-------------+----------------------------------------------------------------\n         gdp |   .0004964   .0000864     5.75   0.000     .0003256    .0006672\n       _cons |   78.89866   1.711204    46.11   0.000     75.51552    82.28181\n------------------------------------------------------------------------------\n```\n\n\n:::\n:::\n\n\nHigher GDP is associated with higher literacy rates, though the relationship is modest in magnitude. Each additional $1000 increase GDP is associated with increases in adult literacy by 0.04.\n\n### Infant Mortality on Literacy\n\n\n::: {.cell}\n\n```{.stata .cell-code}\n* Load wide-format data\nuse \"wb_cleaned_wide.dta\", clear\n\n* Regression: infant mortality on adult literacy\nregress mortality adult_literacy\n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Source |       SS           df       MS      Number of obs   =       141\n-------------+----------------------------------   F(1, 139)       =    380.03\n       Model |  31193.5988         1  31193.5988   Prob > F        =    0.0000\n    Residual |  11409.4203       139  82.0821608   R-squared       =    0.7322\n-------------+----------------------------------   Adj R-squared   =    0.7303\n       Total |  42603.0191       140  304.307279   Root MSE        =    9.0599\n\n--------------------------------------------------------------------------------\n     mortality | Coefficient  Std. err.      t    P>|t|     [95% conf. interval]\n---------------+----------------------------------------------------------------\nadult_literacy |  -.8111436   .0416092   -19.49   0.000    -.8934124   -.7288748\n         _cons |   90.19955   3.594954    25.09   0.000     83.09169    97.30741\n--------------------------------------------------------------------------------\n```\n\n\n:::\n:::\n\n\nThe strong negative relationship between literacy and mortality is consistent with the hypothesis that education plays a role in health outcomes.\n\n## Visualization\n\n\n::: {.cell}\n\n```{.stata .cell-code}\n* Load wide-format data\nuse \"wb_cleaned_wide.dta\", clear\n\n* Scatter plot with regression line and confidence interval\ntwoway (lfitci mortality adult_literacy) ///\n       (scatter mortality adult_literacy, msymbol(circle_hollow)), ///\n    ytitle(\"Infant Mortality (per 1,000 live births)\") ///\n    xtitle(\"Adult Literacy Rate (%)\") ///\n    title(\"Infant Mortality vs. Adult Literacy Across Countries\") ///\n    legend(order(1 \"95% CI\" 2 \"Fitted values\" 3 \"Countries\")) ///\n    graphregion(color(white)) ///\n    scheme(s1mono)\n\ngraph export \"mortality-literacy-scatter.png\", replace width(1200)\n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\nfile\n    /Users/nadhirahendra/Documents/github/nadhira-me/posts/202501_global-development-indi\n    > cators/mortality-literacy-scatter.png saved as PNG format\n```\n\n\n:::\n:::\n\n\n![Infant Mortality vs. Adult Literacy](mortality-literacy-scatter.png){#fig-scatter}\n\n## Gender Gap in Literacy\n\n\n::: {.cell}\n\n```{.stata .cell-code}\n* Load wide-format data\nuse \"wb_cleaned_wide.dta\", clear\n\n* Compare male vs female literacy\nsummarize male_literacy female_literacy\n\n* Calculate the gap\ngenerate literacy_gap = male_literacy - female_literacy\nsummarize literacy_gap, detail\n```\n\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Variable |        Obs        Mean    Std. dev.       Min        Max\n-------------+---------------------------------------------------------\nmale_liter~y |        145    87.76561    15.06481      35.78        100\nfemale_lit~y |        152    82.10739    21.35883      18.87        100\n\n(71 missing values generated)\n\n                        literacy_gap\n-------------------------------------------------------------\n      Percentiles      Smallest\n 1%    -2.989998         -15.82\n 5%    -.8999939      -2.989998\n10%    -.1999969      -2.979996       Obs                 145\n25%            0      -1.475319       Sum of wgt.         145\n\n50%     2.300003                      Mean           5.992751\n                        Largest       Std. dev.      8.032714\n75%     9.750153       25.40344\n90%     18.85879          26.58       Variance        64.5245\n95%           23        28.6043       Skewness       1.018603\n99%      28.6043          29.88       Kurtosis       3.519785\n```\n\n\n:::\n:::\n\n\nThe persistent gap between male and female literacy rates reflects socio-cultural norms in many low- and middle-income countries that historically prioritized boys' education.\n\n# Conclusion\nThe exploratory analysis reveals pattern that gap between the richest and poorest countries isn't just about income but also manifest in infant survival rates, literacy and gender disparities in education. The correlations here can't tell us whether raising GDP would improve health outcomes or whether causal relationships exist between these indicators. Still, exploratory analysis like this can generate hypotheses worth testing with quasi-experimental or experimental methods in future work.\nOn a practical note, I found Stata's syntax efficient for this kind of work. Reshaping and regression tale just a view line of code. \nI hope this serve as a useful reference for data exploration using Stata\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}