project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "posts/**/*.qmd"
    - "notes/**/*.qmd"

website:
  description: "Personal website and blog of Nadhira Azzahra Hendra"
  site-url: "https://nadhira.me"
  title: "Nadhira A. Hendra"
  navbar:
    search: true
    pinned: true
    tools:
      - icon: envelope
        href: mailto:nah2181@columbia.edu
      - icon: github
        href: https://github.com/azzahrandhr
      - icon: linkedin
        href: https://www.linkedin.com/in/azzahrandhr/
    left:
      - text: "|"
      - text: "Projects"
        href: blog.qmd
      - text: "Notes"
        href: notes.qmd
  page-footer:
    border: false
    center: "© 2026 Nadhira A. Hendra · Made with [Quarto](https://quarto.org)"

format:
  html:
    respect-user-color-scheme: true
    theme:
      light: [cosmo, theme-light.scss]
      dark: [cosmo, theme-dark.scss]
execute:
  freeze: auto


  