project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "posts/**/*.qmd"

website:
  description: "Personal website and blog of Nadhira Azzahra Hendra"
  site-url: "https://nadhira.me"
  title: "Nadhira A. Hendra"
  navbar:
    search: true
    pinned: true
    tools:
      - icon: github
        href: https://github.com/azzahrandhr
      - icon: linkedin
        href: https://www.linkedin.com/in/azzahrandhr/
    right:
      - text: "About Me"
        href: index.qmd
      - text: "Posts"
        href: blog.qmd
  page-footer:
    border: false
    center: "© 2026 Nadhira Azzahra Hendra · Made with [Quarto](https://quarto.org)"

format:
  html:
    respect-user-color-scheme: true
    theme:
      light: [cosmo, theme-light.scss]
      dark: [cosmo, theme-dark.scss]
execute:
  freeze: auto


  