{
  "hash": "3feb2bbaca67ed130ae87b33122ba2e7",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Regression Discontinuity in Practice\"\nsubtitle: \"Estimating the Causal Effect of Secondary Education on Self-Employment\"\nauthor: \"Azra\"\ndate: \"2026-01-09\"\ncategories: [econometrics, causal-inference, stata]\nimage: \"rdd-thumbnail.svg\"\nbibliography: references.bib\nformat:\n  html:\n    code-fold: true\n    code-summary: \"Show Stata code\"\n    toc: true\n    toc-depth: 3\n---\n\n## Overview\n\nThis analysis demonstrates the application of **Regression Discontinuity Design (RDD)** to estimate the causal effect of secondary education on self-employment outcomes. RDD is one of the most credible quasi-experimental methods in applied econometrics, exploiting sharp policy cutoffs to identify treatment effects without requiring randomization.\nThe analysis draws on the research context established by @ozier2018, who studied the effects of secondary school attendance in Kenya using the Kenya Certificate of Primary Education (KCPE) exam cutoff. I extend this framework with a hypothetical policy scenario to illustrate the mechanics of RDD estimation.\n\n::: {.callout-note}\n## Key Methodological Contribution\nThis project demonstrates proficiency in implementing RDD analysis in Stata, including visualization of discontinuities, calculation of treatment effects at the cutoff, and critical evaluation of identifying assumptions.\n:::\n\n::: {.callout-tip collapse=\"true\"}\n## Download Stata Do-File\nThe complete Stata code for this analysis is available: [rdd_analysis.do](rdd_analysis.do)\n:::\n\n## The Identification Problem\n\nA naïve comparison of self-employment rates between those who completed secondary school and those who did not would be vulnerable to **omitted variable bias**. Individuals who complete secondary education differ systematically from those who don't—they may come from wealthier families, have higher innate ability, or face different labor market constraints.\n\nConsider one concrete example: age. Secondary school graduates are necessarily at least 18 years old, while those without secondary education include younger individuals who are not yet legally permitted to work full-time. Comparing these groups conflates the education effect with life-cycle employment patterns.\n\n## Regression Discontinuity: The Research Design\n\nRDD offers a solution by exploiting policy rules that create quasi-random assignment to treatment near a cutoff threshold. In Kenya, students who score above a certain threshold on the KCPE exam gain access to secondary schooling, while those just below do not.\n\n### The First Stage: Education Access Jumps at the Cutoff\n\nThe figure below illustrates the relationship between normalized KCPE scores and the probability of completing secondary school:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Probability of Completing Secondary School by KCPE Score (adapted from Ozier 2018)](index_files/figure-html/fig-first-stage-1.png){#fig-first-stage width=672}\n:::\n:::\n\n\nAt the normalized cutoff of 0%, the probability of completing secondary school jumps discontinuously from approximately **32% to 46%**—a 14 percentage point increase. This sharp jump is the \"first stage\" that enables RDD identification.\n\n### The Key Assumption\n\nThe validity of RDD rests on a critical assumption: **the treatment (passing the cutoff) is the only factor that changes discontinuously at the threshold**. All other variables—family background, ability, motivation—should evolve smoothly through the cutoff.\n\nThis assumption could be violated if, for example, students with better-connected families could manipulate their scores to just pass the threshold. In that case, the observed discontinuity would reflect both the education effect and the advantages conferred by family connections.\n\n## Applied RDD: A Policy Scenario\n\nConsider a neighboring country with a stricter policy: only students scoring at least 90% on a national exam can attend secondary school, and all students above this threshold choose to attend.\n\nThe relationship between test scores and self-employment probability follows:\n\n$$\nP(\\text{Self-Employed}) = \\begin{cases} \n0.70 - 0.50 \\times \\text{Score} & \\text{if Score} < 0.9 \\\\\n0.80 - 0.75 \\times \\text{Score} & \\text{if Score} \\geq 0.9\n\\end{cases}\n$$\n\n### Visualizing the Discontinuity\n\n```stata\n* Graph 1: Treatment Assignment (Sharp RDD)\ntwoway function P_SE = (x >= 0.9), range(0 1) ///\n    title(\"Probability of Attending School vs. Test Score\") ///\n    xtitle(\"Test Score\") ytitle(\"P(Attending Secondary School)\") ///\n    xlabel(0(.1)1, format(%5.2f)) ylabel(0(.1)1, format(%5.2f))\n\n* Graph 2: Outcome Variable with Discontinuity\ntwoway function (0.70 - 0.50*x)*(x < 0.9) + (0.80 - 0.75*x)*(x >= 0.9), ///\n    range(0 1) ///\n    title(\"Probability of Being Self-Employed vs. Test Score\") ///\n    xtitle(\"Test Score\") ytitle(\"P(Self-Employed)\")\n```\n\n\n::: {.cell layout-ncol=\"2\"}\n::: {.cell-output-display}\n![Regression Discontinuity Design: Treatment and Outcome](index_files/figure-html/fig-rdd-panels-1.png){#fig-rdd-panels-1 width=672}\n:::\n\n::: {.cell-output-display}\n![Regression Discontinuity Design: Treatment and Outcome](index_files/figure-html/fig-rdd-panels-2.png){#fig-rdd-panels-2 width=672}\n:::\n:::\n\n\n### Calculating the Treatment Effect\n\nThe causal effect of secondary education on self-employment is identified by the **discontinuous jump in outcomes at the cutoff**. At the threshold (Score = 0.9):\n\n- **Just below the cutoff:** $P(\\text{Self-Employed}) = 0.70 - 0.50(0.9) = 0.25$ (25%)\n- **Just above the cutoff:** $P(\\text{Self-Employed}) = 0.80 - 0.75(0.9) = 0.125$ (12.5%)\n\nThe estimated treatment effect is:\n\n$$\\hat{\\tau}_{RDD} = 0.125 - 0.25 = -0.125$$\n\n**Interpretation:** Secondary school attendance reduces the probability of self-employment by **12.5 percentage points** for students at the margin of eligibility.\n\n::: {.callout-important}\n## Local Average Treatment Effect (LATE)\nThis estimate is a *local* effect—it applies specifically to students near the cutoff (those scoring around 90%). Generalizing to students with very different scores requires additional assumptions that may not hold.\n:::\n\n### External Validity Concerns\n\nThe government might want to use this estimate to predict how extending secondary education to poor-performing students would affect their employment outcomes. Economists would be skeptical for several reasons:\n\n1. **Treatment effect heterogeneity:** Students near the 90% cutoff are fundamentally different from those scoring much lower. They likely have different skill profiles, family backgrounds, and labor market opportunities.\n\n2. **Different counterfactual outcomes:** Low-scoring students might have different self-employment options available to them even without secondary education.\n\n3. **Selection into self-employment:** The reasons high-ability students choose (or avoid) self-employment may differ from those of lower-ability students.\n\nWithout a randomized control trial or additional quasi-experimental variation, extrapolating the RDD estimate to a different population remains speculative.\n\n## Supplementary Analysis: Development Indicators\n\nThe project also includes analysis of World Bank development indicators, examining the relationship between GDP per capita, literacy rates, and infant mortality across 212 countries.\n\n### Data Processing\n\n```stata\n* Read and clean World Bank indicators data\nimport delimited \"wb_indicators_2015_2024.csv\", varnames(1) numericcols(5/14)\n\n* Remove regional aggregates (keep only country-level data)\ngenerate id = _n\nkeep if id < 1086  // Removes 245 regional aggregates\n\n* Reshape and keep most recent value for each country-indicator pair\nreshape long yr, i(id) j(year)\nrename yr seriesvalue\nkeep if seriesvalue < .\n\ngsort seriescode countrycode -year\nby seriescode countrycode: keep if _n == 1\n```\n\n### Key Findings\n\nThe descriptive analysis reveals stark global inequalities:\n\n| Indicator | High-Income (Top 50) | Low-Income (Bottom 50) |\n|-----------|---------------------|------------------------|\n| Mean Adult Literacy | 97.8% | 65.0% |\n| Literacy Range | 92.4% – 100% | 27.3% – 99.6% |\n| Mean Infant Mortality | 3.4 per 1,000 | 39.7 per 1,000 |\n| Mortality Range | 1.4 – 11.4 | 14.3 – 72.6 |\n\n: Comparison of Development Outcomes by Income Group {#tbl-inequality}\n\nThe gap is especially striking for infant mortality: the *highest* mortality rate among wealthy countries (11.4 per 1,000) is *lower* than the *lowest* rate among poor countries (14.3 per 1,000). This non-overlapping distribution underscores systemic differences in health infrastructure.\n\n### Regression Results\n\n```stata\n* Infant mortality on GDP per capita\nregress mortality_rate gdp_per_capita\n\n* Literacy on GDP per capita  \nregress adult_literacy_rate gdp_per_capita\n```\n\n| Outcome | Coefficient | Std. Error | 95% CI | p-value |\n|---------|-------------|------------|--------|---------|\n| Infant Mortality | −0.00027 | 0.000037 | [−0.0003, −0.0002] | <0.001 |\n| Adult Literacy | 0.00050 | 0.000086 | [0.0003, 0.0007] | <0.001 |\n\n: Relationship Between GDP Per Capita and Development Outcomes {#tbl-regression}\n\nEach additional $1,000 in GDP per capita is associated with 0.27 fewer infant deaths per 1,000 births and a 0.5 percentage point increase in adult literacy.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Infant Mortality and Adult Literacy Across Countries](index_files/figure-html/fig-literacy-mortality-1.png){#fig-literacy-mortality width=672}\n:::\n:::\n\n\n## Conclusion\n\nThis analysis demonstrates the power of Regression Discontinuity Design for causal inference in settings where randomization is not feasible. The key takeaways:\n\n1. **RDD exploits institutional rules** to create quasi-experimental variation, enabling credible causal estimates without random assignment.\n\n2. **The identifying assumption**—that nothing else changes discontinuously at the cutoff—must be carefully evaluated and defended.\n\n3. **RDD estimates are local**: they identify effects for individuals near the margin of eligibility, not necessarily for the broader population.\n\n4. **Visualization is essential**: graphing both the first stage (treatment assignment) and reduced form (outcome) relationships makes the research design transparent.\n\nFor policy applications, RDD provides high internal validity but limited external validity. Extending findings to different populations requires additional evidence or assumptions about treatment effect heterogeneity.\n\n## References\n\n::: {#refs}\n:::\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}